name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'destroy' to confirm"
        required: true
        default: ""

permissions:
  id-token: write
  contents: read

env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  TF_CLI_ARGS_init: -no-color
  TF_CLI_ARGS_destroy: -no-color -auto-approve
  # Visible, easy-to-edit variables
  AWS_REGION: us-east-1 # change as needed
  TF_STATE_BUCKET: aws-basics-labs-tf-state # change as needed
  TF_STATE_KEY: aws-basics-labs/dev/terraform.tfstate # change as needed
  TF_STATE_LOCK_TABLE: aws-basics-labs-tf-locks # change as needed
  TF_VAR_aws_region: ${{ env.AWS_REGION }}

jobs:
  destroy:
    if: github.event.inputs.confirm == 'destroy'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::575960430633:role/GitHubActionsDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Show config
        run: |
          echo "AWS_REGION=$AWS_REGION"
          echo "TF_STATE_BUCKET=$TF_STATE_BUCKET"
          echo "TF_STATE_KEY=$TF_STATE_KEY"
          echo "TF_STATE_LOCK_TABLE=$TF_STATE_LOCK_TABLE"

      - name: Terraform Init (S3 backend)
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ env.TF_STATE_KEY }}" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ env.TF_STATE_LOCK_TABLE }}" \
            -backend-config="encrypt=true"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve